name: Post merge

on:
  push:
    branches: [ "develop" ]

jobs:
  allChecks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run all checks
    run: gradle check --stacktrace
    
    - uses: actions/upload-artifact@v3
      with:
      name: lint-report.html  
      path: app/build/reports/lint-results.html
            
    - name: Upload Test results
      uses: actions/upload-artifact@v3
      with:
        name: test-report.html
        path: app/build/reports/tests/testDebugUnitTest/index.html
            
    
   instrumentationTests:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run instrumentation tests
     uses: reactivecircus/android-emulator-runner@v2
       with:
        api-level: 29
        script: gradle connectedChech --stacktrace
           
    deploy:
      run-ons: ubuntu-latest
      needs: [allChecks, instrumentationTests]
      steps:
        - uses: actions/checkout@v3
        - name: Build Snapshot
          run: gradle assemble --stacktrace
          - uses: actions/upload-artifact@v3
          with:
            name: app-release-SNAPSHOT.apk
            path: app/build/outputs/apk/release/app-release-unsigned.apk
